class Classifier(object):
    def __init__(self):
        pass
    
    #returns the probability that "testData" was generated by "user"
    def compare(self, user, testData):
        probability = 0;
        #do checks here
        return probability;
